spring:
    application:
        name: admin-config
    cloud:
        config:
            server:
                git:
                    uri: https://git.oschina.net/geek_qi/AG-Config.git

server:
    port: 8088 #启动端口
